name: CI/CD 16x

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm i

      - name: prettier
        run: npm run prettier:check

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm i

      - name: eslint
        run: npm run lint:check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm i

      - name: Copy Config
        run: cp config.example.json config.json

      - name: Test Build
        run: npm run build

  scss:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm i

      - name: Test SCSS
        run: npm run scss
